Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
newckpt = cpdir + '/checkpoint.pt'
newcalc = OCPCalculator(checkpoint_path=newckpt, cpu=False)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[17], line 2[0m
[1;32m      1[0m newckpt [38;5;241m=[39m cpdir [38;5;241m+[39m [38;5;124m'[39m[38;5;124m/checkpoint.pt[39m[38;5;124m'[39m
[0;32m----> 2[0m newcalc [38;5;241m=[39m [43mOCPCalculator[49m[43m([49m[43mcheckpoint_path[49m[38;5;241;43m=[39;49m[43mnewckpt[49m[43m,[49m[43m [49m[43mcpu[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m

File [0;32m~/work/ocp/ocp/ocpmodels/common/relaxation/ase_utils.py:140[0m, in [0;36mOCPCalculator.__init__[0;34m(self, config_yml, checkpoint_path, model_name, local_cache, trainer, cutoff, max_neighbors, cpu, seed)[0m
[1;32m    137[0m         config[[38;5;124m"[39m[38;5;124mdataset[39m[38;5;124m"[39m] [38;5;241m=[39m config[[38;5;124m"[39m[38;5;124mdataset[39m[38;5;124m"[39m][38;5;241m.[39mget([38;5;124m"[39m[38;5;124mtrain[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[1;32m    138[0m [38;5;28;01melse[39;00m:
[1;32m    139[0m     [38;5;66;03m# Loads the config from the checkpoint directly (always on CPU).[39;00m
[0;32m--> 140[0m     checkpoint [38;5;241m=[39m [43mtorch[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[43mcheckpoint_path[49m[43m,[49m[43m [49m[43mmap_location[49m[38;5;241;43m=[39;49m[43mtorch[49m[38;5;241;43m.[39;49m[43mdevice[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mcpu[39;49m[38;5;124;43m"[39;49m[43m)[49m[43m)[49m
[1;32m    141[0m     config [38;5;241m=[39m checkpoint[[38;5;124m"[39m[38;5;124mconfig[39m[38;5;124m"[39m]
[1;32m    143[0m [38;5;28;01mif[39;00m trainer [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/torch/serialization.py:998[0m, in [0;36mload[0;34m(f, map_location, pickle_module, weights_only, mmap, **pickle_load_args)[0m
[1;32m    995[0m [38;5;28;01mif[39;00m [38;5;124m'[39m[38;5;124mencoding[39m[38;5;124m'[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m pickle_load_args[38;5;241m.[39mkeys():
[1;32m    996[0m     pickle_load_args[[38;5;124m'[39m[38;5;124mencoding[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;124m'[39m[38;5;124mutf-8[39m[38;5;124m'[39m
[0;32m--> 998[0m [38;5;28;01mwith[39;00m [43m_open_file_like[49m[43m([49m[43mf[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m opened_file:
[1;32m    999[0m     [38;5;28;01mif[39;00m _is_zipfile(opened_file):
[1;32m   1000[0m         [38;5;66;03m# The zipfile reader is going to advance the current file position.[39;00m
[1;32m   1001[0m         [38;5;66;03m# If we want to actually tail call to torch.jit.load, we need to[39;00m
[1;32m   1002[0m         [38;5;66;03m# reset back to the original position.[39;00m
[1;32m   1003[0m         orig_position [38;5;241m=[39m opened_file[38;5;241m.[39mtell()

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/torch/serialization.py:445[0m, in [0;36m_open_file_like[0;34m(name_or_buffer, mode)[0m
[1;32m    443[0m [38;5;28;01mdef[39;00m [38;5;21m_open_file_like[39m(name_or_buffer, mode):
[1;32m    444[0m     [38;5;28;01mif[39;00m _is_path(name_or_buffer):
[0;32m--> 445[0m         [38;5;28;01mreturn[39;00m [43m_open_file[49m[43m([49m[43mname_or_buffer[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m
[1;32m    446[0m     [38;5;28;01melse[39;00m:
[1;32m    447[0m         [38;5;28;01mif[39;00m [38;5;124m'[39m[38;5;124mw[39m[38;5;124m'[39m [38;5;129;01min[39;00m mode:

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/torch/serialization.py:426[0m, in [0;36m_open_file.__init__[0;34m(self, name, mode)[0m
[1;32m    425[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, name, mode):
[0;32m--> 426[0m     [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m([38;5;28;43mopen[39;49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'fine-tuning/checkpoints/2024-04-14-18-46-24-ft-oxides/checkpoint.pt'

