Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ocpmodels.common.relaxation.ase_utils import OCPCalculator
from ocpmodels.models.model_registry import model_name_to_local_file
import os

checkpoint_path = model_name_to_local_file('EquiformerV2 (31M) All+MD', local_cache='/tmp/ocp_checkpoints/')

os.makedirs(f"data/{bulk}_{adsorbate}", exist_ok=True)

# Define the calculator
calc = OCPCalculator(checkpoint=checkpoint_path) # if you have a gpu, add `cpu=False` to speed up calculations

adslabs = [*heuristic_adslabs.atoms_list, *random_adslabs.atoms_list]
# Set up the calculator
for idx, adslab in enumerate(adslabs):
    adslab.calc = calc
    opt = BFGS(adslab, trajectory=f"data/{bulk}_{adsorbate}/{idx}.traj")
    opt.run(fmax=0.05, steps=100) # For the AdsorbML results we used fmax = 0.02 and steps = 300, but we will use less strict values for brevity.
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 10[0m
[1;32m      7[0m os[38;5;241m.[39mmakedirs([38;5;124mf[39m[38;5;124m"[39m[38;5;124mdata/[39m[38;5;132;01m{[39;00mbulk[38;5;132;01m}[39;00m[38;5;124m_[39m[38;5;132;01m{[39;00madsorbate[38;5;132;01m}[39;00m[38;5;124m"[39m, exist_ok[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m      9[0m [38;5;66;03m# Define the calculator[39;00m
[0;32m---> 10[0m calc [38;5;241m=[39m [43mOCPCalculator[49m[43m([49m[43mcheckpoint[49m[38;5;241;43m=[39;49m[43mcheckpoint_path[49m[43m)[49m [38;5;66;03m# if you have a gpu, add `cpu=False` to speed up calculations[39;00m
[1;32m     12[0m adslabs [38;5;241m=[39m [[38;5;241m*[39mheuristic_adslabs[38;5;241m.[39matoms_list, [38;5;241m*[39mrandom_adslabs[38;5;241m.[39matoms_list]
[1;32m     13[0m [38;5;66;03m# Set up the calculator[39;00m

[0;31mTypeError[0m: OCPCalculator.__init__() got an unexpected keyword argument 'checkpoint'

